name: Add domain to allowlist
description: Propose a government/public-institution domain to add
title: "allow: <domain.tld>"
labels: ["allowlist"]
body:
  - type: input
    id: domain
    attributes:
      label: Domain
      description: "Domain/hostname only (e.g., 'example.gov'). No URLs or IPs."
      placeholder: "example.gov"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why is this trustworthy?
      description: "Short justification and what this domain represents (agency, ministry, university, etc.)."
      placeholder: "Official portal of the Ministry of X…"
    validations:
      required: false
